"""ipinfo table

Revision ID: 1ad5f76036af
Revises: d2ac9a859643
Create Date: 2020-10-29 14:55:40.079817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad5f76036af'
down_revision = 'd2ac9a859643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('hostname', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipinfo_ip'), 'ipinfo', ['ip'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipinfo_ip'), table_name='ipinfo')
    op.drop_table('ipinfo')
    # ### end Alembic commands ###
